const categories = [
  ['all','▦','全部工具'],['network-cat','⌁','网络与系统'],['image','◫','图片与媒体'],['generator','◇','信息生成'],['japan','あ','日本专区'],['office','✎','办公效率'],['account','◎','账号与网站']
];
const tools = [
  {id:'network',cat:'network-cat',icon:'⌁',title:'IP 与本机网络',desc:'查看本机 IP、网卡与公网地址',color:'blue'},
  {id:'proxy',cat:'network-cat',icon:'⇄',title:'电脑代理',desc:'保存节点、识别二维码并切换配置',color:'purple'},
  {id:'hotspot',cat:'network-cat',icon:'◉',title:'移动热点',desc:'查看 Windows 热点设置与指引',color:'orange'},
  {id:'cleanup',cat:'network-cat',icon:'✦',title:'磁盘清理',desc:'安全检查 C 盘并打开系统清理',color:'red'},
  {id:'ins',cat:'image',icon:'↓',title:'Instagram 图片',desc:'解析公开帖子链接与下载提示',color:'purple'},
  {id:'upscale',cat:'image',icon:'⌗',title:'图片高清放大',desc:'本地 2×/4× 插值放大与导出',color:'blue'},
  {id:'gif',cat:'image',icon:'▶',title:'GIF 制作',desc:'多张图片合成与参数设置',color:'orange'},
  {id:'screenshot',cat:'image',icon:'⌑',title:'截图与 OCR',desc:'截取屏幕并提取图片文字',color:'blue'},
  {id:'phone',cat:'generator',icon:'☎',title:'电话号码生成',desc:'按国家生成测试用号码',color:'blue'},
  {id:'address',cat:'generator',icon:'⌂',title:'地址生成',desc:'生成多国格式化示例地址',color:'orange'},
  {id:'enname',cat:'generator',icon:'Aa',title:'英文名字生成',desc:'性别、风格与数量可选',color:'purple'},
  {id:'jpname',cat:'japan',icon:'あ',title:'日本名字生成',desc:'汉字、片假名、罗马字、网名',color:'red'},
  {id:'phrases',cat:'japan',icon:'話',title:'日本常用语 100 条',desc:'场景分类、假名与中文释义',color:'orange'},
  {id:'emoji',cat:'japan',icon:'顔',title:'日本常用表情',desc:'颜文字分类与一键复制',color:'purple'},
  {id:'jpknowledge',cat:'japan',icon:'日',title:'日本常识',desc:'生活、交通、礼仪与办事指南',color:'blue'},
  {id:'culture',cat:'japan',icon:'祭',title:'日本文化',desc:'节日、饮食、职场和社交文化',color:'red'},
  {id:'taboo',cat:'japan',icon:'!',title:'日本忌讳',desc:'旅行与社交注意事项',color:'orange'},
  {id:'likes',cat:'japan',icon:'♡',title:'日本人喜欢',desc:'沟通偏好与流行兴趣参考',color:'purple'},
  {id:'stockbasics',cat:'japan',icon:'¥',title:'日本股市常识',desc:'交易制度、指数与风险知识',color:'blue'},
  {id:'stock',cat:'japan',icon:'↗',title:'日本股票查询',desc:'股票代码、指标与分析清单',color:'red'},
  {id:'banks',cat:'japan',icon:'銀',title:'日本银行',desc:'主要银行与开户资料导航',color:'blue'},
  {id:'brokers',cat:'japan',icon:'証',title:'日本证券',desc:'券商比较维度与官方入口',color:'purple'},
  {id:'notebook',cat:'office',icon:'✎',title:'加密记事本',desc:'AES-GCM 密码锁与本地保存',color:'purple'},
  {id:'counter',cat:'office',icon:'123',title:'字数统计',desc:'字符、单词、段落和阅读时间',color:'blue'},
  {id:'passwordgen',cat:'office',icon:'＊',title:'安全密码生成',desc:'在本机生成高强度随机密码',color:'red'},
  {id:'translate',cat:'office',icon:'文',title:'谷歌翻译',desc:'输入文字并打开翻译结果',color:'orange'},
  {id:'totp',cat:'account',icon:'6',title:'2FA 验证码',desc:'本地生成 TOTP 动态验证码',color:'red'},
  {id:'mail',cat:'account',icon:'@',title:'邮箱中心',desc:'Gmail 与 Outlook 官方登录入口',color:'blue'},
  {id:'tempmail',cat:'account',icon:'✉',title:'临时邮箱',desc:'创建一次性邮箱并实时查看邮件',color:'orange'},
  {id:'telegram',cat:'account',icon:'➤',title:'Telegram 账号',desc:'打开官方会话管理与注销指引',color:'purple'},
  {id:'sites',cat:'account',icon:'☆',title:'常用网站',desc:'邮箱、Telegram、输入法等快捷入口',color:'orange'}
  ,{id:'settings',cat:'office',icon:'⚙',title:'设置与升级中心',desc:'检查并升级内核、下载组件和应用依赖',color:'blue'}
];
const $=s=>document.querySelector(s), grid=$('#grid'), modal=$('#modal');
if(localStorage.getItem('theme')==='light')document.body.classList.add('light');
$('#categories').innerHTML=categories.map((x,i)=>`<button data-cat="${x[0]}" class="${i?'':'active'}"><span>${x[1]}</span>${x[2]}</button>`).join('');
function render(cat='all', q=''){
  const rows=tools.filter(t=>(cat==='all'||t.cat===cat)&&(`${t.title}${t.desc}`.toLowerCase().includes(q.toLowerCase())));
  grid.innerHTML=rows.map(t=>`<button class="tool-card" data-open="${t.id}" data-color="${t.color}"><span class="tool-icon">${t.icon}</span><h3>${t.title}</h3><p>${t.desc}</p></button>`).join('');
  $('#count').textContent=`${rows.length} 个工具`;
}
render();
document.addEventListener('click',e=>{const open=e.target.closest('[data-open]');if(open)showTool(open.dataset.open);const cat=e.target.closest('[data-cat]');if(cat){document.querySelectorAll('[data-cat]').forEach(x=>x.classList.remove('active'));cat.classList.add('active');render(cat.dataset.cat,$('#search').value)}});
$('#search').addEventListener('input',e=>render('all',e.target.value));
$('#close').onclick=()=>modal.close();
document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='k'){e.preventDefault();$('#search').focus()}if(e.key==='Escape'&&modal.open)modal.close()});
setInterval(()=>$('#clock').textContent=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long',hour:'2-digit',minute:'2-digit'}).format(new Date()),1000);
const toast=s=>{const el=$('#toast');el.textContent=s;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1700)};
const copy=async s=>{await navigator.clipboard.writeText(s);toast('已复制到剪贴板')};
const rand=a=>a[Math.floor(Math.random()*a.length)];
const open=u=>window.toolbox?.open(u)||window.open(u,'_blank');
function shell(html){return html}

const countries={US:{code:'+1',phone:'(###) ###-####',city:['Seattle, WA','Austin, TX','Boston, MA'],street:['Oak Street','Maple Avenue','Lake Road']},CA:{code:'+1',phone:'(###) ###-####',city:['Toronto, ON','Vancouver, BC','Montréal, QC'],street:['King Street','Granville Street','Rue Sainte-Catherine']},JP:{code:'+81',phone:'##-####-####',city:['東京都渋谷区','大阪府大阪市北区','福岡県福岡市'],street:['神南1-2-3','梅田2-4-8','天神3-1-6']},KR:{code:'+82',phone:'##-####-####',city:['서울특별시','부산광역시','인천광역시'],street:['테헤란로 123','해운대로 45','송도길 18']},GB:{code:'+44',phone:'#### ### ####',city:['London','Manchester','Edinburgh'],street:['King Street','High Road','Park Lane']},DE:{code:'+49',phone:'#### ########',city:['Berlin','München','Hamburg'],street:['Hauptstraße','Gartenweg','Berliner Straße']},FR:{code:'+33',phone:'# ## ## ## ##',city:['Paris','Lyon','Nice'],street:['Rue de Rivoli','Avenue Victor Hugo','Rue Nationale']},CN:{code:'+86',phone:'1## #### ####',city:['北京市朝阳区','上海市浦东新区','广东省深圳市'],street:['建国路88号','世纪大道100号','科技南路18号']},AU:{code:'+61',phone:'# #### ####',city:['Sydney NSW','Melbourne VIC','Brisbane QLD'],street:['George Street','Collins Street','Queen Street']},NZ:{code:'+64',phone:'## ### ####',city:['Auckland','Wellington','Christchurch'],street:['Queen Street','Lambton Quay','Colombo Street']},SG:{code:'+65',phone:'#### ####',city:['Singapore'],street:['Orchard Road','Marina Boulevard','Serangoon Road']},IN:{code:'+91',phone:'##### #####',city:['Mumbai','Delhi','Bengaluru'],street:['MG Road','Park Street','Linking Road']},TH:{code:'+66',phone:'##-###-####',city:['Bangkok','Chiang Mai','Phuket'],street:['Sukhumvit Road','Nimman Road','Patong Road']},VN:{code:'+84',phone:'### ### ####',city:['Hà Nội','TP. Hồ Chí Minh','Đà Nẵng'],street:['Nguyễn Huệ','Trần Hưng Đạo','Lê Lợi']},BR:{code:'+55',phone:'(##) #####-####',city:['São Paulo SP','Rio de Janeiro RJ','Brasília DF'],street:['Avenida Paulista','Rua Copacabana','Eixo Monumental']},MX:{code:'+52',phone:'### ### ####',city:['Ciudad de México','Guadalajara','Monterrey'],street:['Avenida Reforma','Avenida Vallarta','Avenida Constitución']},ES:{code:'+34',phone:'### ### ###',city:['Madrid','Barcelona','Valencia'],street:['Calle Mayor','Passeig de Gràcia','Carrer de Colón']},IT:{code:'+39',phone:'### ### ####',city:['Roma','Milano','Firenze'],street:['Via Roma','Corso Buenos Aires','Via dei Calzaiuoli']},NL:{code:'+31',phone:'## ########',city:['Amsterdam','Rotterdam','Utrecht'],street:['Damrak','Coolsingel','Oudegracht']},SE:{code:'+46',phone:'##-### ## ##',city:['Stockholm','Göteborg','Malmö'],street:['Drottninggatan','Avenyn','Södergatan']},AE:{code:'+971',phone:'## ### ####',city:['Dubai','Abu Dhabi','Sharjah'],street:['Sheikh Zayed Road','Corniche Road','Al Wahda Street']}};
function digits(pattern){return pattern.replace(/#/g,()=>Math.floor(Math.random()*10))}
const englishNames={male:['Oliver','James','Henry','Noah','William','Benjamin','Lucas','Theodore','Liam','Ethan','Jack','George','Arthur','Leo','Daniel'],female:['Emma','Olivia','Sophia','Amelia','Charlotte','Mia','Ava','Isla','Grace','Lily','Emily','Chloe','Sophie','Ella','Zoe']};
const englishLast={us:['Smith','Johnson','Brown','Davis','Miller','Wilson','Anderson','Clark','Lewis','Walker'],uk:['Jones','Williams','Taylor','Davies','Evans','Thomas','Roberts','Hughes','Edwards','Green'],international:['Martin','Garcia','Kim','Patel','Lee','Silva','Rossi','Müller','Dubois','Sato']};
const jpFirst=[['Haruto','ハルト','陽翔'],['Ren','レン','蓮'],['Sota','ソウタ','蒼太'],['Yui','ユイ','結衣'],['Aoi','アオイ','葵'],['Sakura','サクラ','桜'],['Rin','リン','凛'],['Hina','ヒナ','陽菜']], jpLast=[['Sato','サトウ','佐藤'],['Suzuki','スズキ','鈴木'],['Takahashi','タカハシ','高橋'],['Tanaka','タナカ','田中'],['Watanabe','ワタナベ','渡辺']];

const simpleInfo={
  hotspot:['Windows 11：设置 → 网络和 Internet → 移动热点','建议使用 WPA2/WPA3，并设置强密码','公司电脑启用前请确认 IT 管理策略'],
  cleanup:['先运行 Windows“存储感知”查看可释放空间','优先清理临时文件、缩略图和回收站','不要手动删除 Windows、Program Files 或未知系统目录','重要文件清理前请备份'],
  jpknowledge:['电车内通常保持安静，手机调为静音','垃圾分类规则因市区町村而异','多数场合无需支付小费','便利店可处理缴费、取票、复印等事务','排队与守时非常受重视'],
  culture:['新年（正月）是最重要的传统节期之一','赏樱常与春季聚会相连','职场重视“报・连・相”：报告、联络、商量','送礼注重包装、季节感与回礼','饮食前后常说「いただきます」「ごちそうさま」'],
  taboo:['不要把筷子直插在米饭中','避免在公共交通里大声通话','进入住宅及部分餐厅前要脱鞋','温泉入池前先洗净身体，毛巾不入池','未经允许不要近距离拍摄陌生人'],
  likes:['清晰、礼貌、不给对方压力的沟通','季节限定商品和在地特色','整洁的包装与细节感','动漫、游戏、音乐、体育等兴趣圈层差异很大','此页仅供破冰参考，不应把个人偏好按国籍概括'],
  stockbasics:['东京证券交易所主要市场分为 Prime、Standard、Growth','日经 225 是价格加权指数；TOPIX 更广泛反映市场','通常以 100 股为一个交易单位，个别服务支持碎股','日本股票有价格涨跌幅限制，范围随前收盘价变化','投资涉及风险，本工具只提供资料整理，不构成投资建议'],
  banks:['三菱UFJ银行 — mufg.jp','三井住友银行 — smbc.co.jp','瑞穗银行 — mizuhobank.co.jp','日本邮政银行 — jp-bank.japanpost.jp','乐天银行 — rakuten-bank.co.jp'],
  brokers:['野村证券 — nomura.co.jp','大和证券 — daiwa.jp','SBI证券 — sbisec.co.jp','乐天证券 — rakuten-sec.co.jp','松井证券 — matsui.co.jp']
};

const phrasesBase=[['こんにちは','你好'],['ありがとうございます','谢谢'],['すみません','不好意思／劳驾'],['おはようございます','早上好'],['こんばんは','晚上好'],['おやすみなさい','晚安'],['さようなら','再见'],['また会いましょう','下次见'],['はじめまして','初次见面'],['よろしくお願いします','请多关照'],['はい','是'],['いいえ','不是'],['わかりました','明白了'],['わかりません','不明白'],['大丈夫です','没问题'],['お願いします','拜托了'],['もう一度お願いします','请再说一次'],['ゆっくり話してください','请慢点说'],['日本語が少し話せます','会说一点日语'],['英語を話せますか','会说英语吗'],['これは何ですか','这是什么'],['いくらですか','多少钱'],['これをください','请给我这个'],['カードは使えますか','可以刷卡吗'],['レシートをください','请给我小票'],['試着してもいいですか','可以试穿吗'],['免税できますか','可以免税吗'],['駅はどこですか','车站在哪里'],['トイレはどこですか','洗手间在哪里'],['ここへ行きたいです','我想去这里'],['道に迷いました','我迷路了'],['右です','在右边'],['左です','在左边'],['まっすぐです','直走'],['次の駅は何ですか','下一站是什么'],['切符を一枚ください','请给我一张票'],['何時に出発しますか','几点出发'],['予約しています','我有预约'],['空いていますか','有空位吗'],['チェックインお願いします','请办理入住'],['Wi-Fiはありますか','有无线网络吗'],['荷物を預けたいです','我想寄存行李'],['メニューをください','请给我菜单'],['おすすめは何ですか','有什么推荐'],['水をください','请给我水'],['いただきます','我开动了'],['ごちそうさまでした','多谢款待'],['辛くしないでください','请不要做辣'],['アレルギーがあります','我有过敏'],['お会計お願いします','请结账'],
['持ち帰りできますか','可以打包吗'],['一人です','一位'],['二人です','两位'],['禁煙席をお願いします','请安排无烟座'],['写真を撮ってもいいですか','可以拍照吗'],['写真を撮ってください','请帮我拍照'],['助けてください','请帮帮我'],['警察を呼んでください','请报警'],['救急車を呼んでください','请叫救护车'],['病院はどこですか','医院在哪里'],['気分が悪いです','我不舒服'],['薬局はどこですか','药店在哪里'],['財布をなくしました','钱包丢了'],['パスポートをなくしました','护照丢了'],['忘れ物をしました','我遗失了物品'],['今日','今天'],['明日','明天'],['昨日','昨天'],['今何時ですか','现在几点'],['何時までですか','营业到几点'],['休みはいつですか','什么时候休息'],['天気がいいですね','天气真好'],['暑いですね','真热啊'],['寒いですね','真冷啊'],['雨が降っています','正在下雨'],['ちょっと待ってください','请稍等'],['急いでいます','我赶时间'],['時間があります','我有时间'],['本当ですか','真的吗'],['もちろんです','当然'],['たぶん','也许'],['いいですね','很好啊'],['おいしいです','很好吃'],['楽しいです','很开心'],['かわいいです','很可爱'],['きれいです','很漂亮／干净'],['すごいです','太厉害了'],['お疲れさまです','辛苦了'],['失礼します','打扰／告辞了'],['お先に失礼します','我先告辞了'],['お久しぶりです','好久不见'],['元気ですか','你好吗'],['元気です','我很好'],['名前は何ですか','你叫什么名字'],['私は旅行者です','我是游客'],['中国から来ました','我来自中国'],['住所を書いてください','请写下地址'],['電話番号を教えてください','请告诉我电话号码'],['充電できますか','可以充电吗'],['無料ですか','免费吗']];

async function showTool(id){
  const t=tools.find(x=>x.id===id);$('#modalIcon').textContent=t.icon;$('#modalTitle').textContent=t.title;$('#modalDesc').textContent=t.desc;$('#modalBody').innerHTML=await bodyFor(id);modal.showModal();bindTool(id);
}
async function bodyFor(id){
  if(id==='network'){let d={hostname:'浏览器模式',platform:'请使用 Electron 启动',rows:[]};try{d=await window.toolbox.network()}catch{}return `<div class="result">主机：${d.hostname}\n系统：${d.platform}\n${d.rows.map(x=>`${x.name} · ${x.family}\n${x.address}`).join('\n\n')||'未读取到本机网卡'}</div><div class="actions"><button class="primary" id="publicIp">查询公网 IP</button></div><div id="out"></div>`}
  if(id==='phone')return `<div class="field"><label>国家／地区</label><select id="country">${Object.keys(countries).map(k=>`<option>${k}</option>`).join('')}</select></div>${quantityPicker()}<button class="primary execute" id="generate">生成电话号码</button><div id="out"></div>`;
  if(id==='address')return `<div class="field"><label>国家／地区</label><select id="country">${Object.keys(countries).map(k=>`<option>${k}</option>`).join('')}</select></div>${quantityPicker()}<button class="primary execute" id="generate">生成地址数据</button><div id="out"></div>`;
  if(id==='enname')return `<div class="form-row"><div class="field"><label>性别风格</label><select id="nameGender"><option value="any">随机</option><option value="male">男性</option><option value="female">女性</option></select></div><div class="field"><label>地区风格</label><select id="nameRegion"><option value="us">美国</option><option value="uk">英国</option><option value="international">国际</option></select></div></div>${quantityPicker()}<button class="primary execute" id="generate">生成英文名字</button><div id="out"></div>`;
  if(id==='jpname')return `<div class="field"><label>网名风格</label><select id="style"><option>简洁</option><option>可爱</option><option>游戏</option></select></div>${quantityPicker()}<button class="primary execute" id="generate">一键生成全部格式</button><div id="out"></div>`;
  if(id==='counter')return `<textarea id="text" placeholder="在这里输入或粘贴文字…"></textarea><div id="stats" class="result">字符 0 · 单词 0 · 行数 0 · 阅读 0 分钟</div>`;
  if(id==='passwordgen')return `<div class="field"><label>密码长度</label><select id="passLength"><option>16</option><option>24</option><option>32</option><option>48</option></select></div><button class="primary" id="makePassword">生成安全密码</button><div id="out"></div>`;
  if(id==='notebook')return `<div class="notice">内容使用浏览器 Web Crypto 的 AES-GCM 加密后保存在本机。忘记密码将无法恢复。</div><div class="field"><label>密码</label><input type="password" id="password" placeholder="输入密码"></div><textarea id="note" placeholder="写下只属于你的内容…"></textarea><div class="actions"><button class="primary" id="saveNote">加密保存</button><button class="secondary" id="loadNote">解锁读取</button><button class="secondary" id="clearNote">清空当前</button></div>`;
  if(id==='totp')return `<div class="notice">密钥只在当前页面本地计算，不会上传。请勿在他人电脑保存密钥。</div><div class="field"><label>Base32 密钥</label><input id="secret" placeholder="例如 JBSWY3DPEHPK3PXP"></div><button class="primary" id="makeTotp">生成验证码</button><div id="out"></div>`;
  if(id==='tempmail')return `<div class="notice">邮箱由 Mail.tm 提供，仅用于合法的短期收件。地址和登录令牌只保留在当前应用会话中，关闭软件后不再保存。</div><div id="tempIdentity" class="result">还没有临时邮箱</div><div class="actions"><button class="primary" id="createTempMail">创建新邮箱</button><button class="secondary" id="copyTempMail" disabled>复制地址</button><button class="secondary" id="refreshTempMail" disabled>刷新收件箱</button></div><div id="out"></div><p style="color:var(--muted);font-size:11px">服务提供方：<a href="#" id="mailTmLink" style="color:var(--cyan)">Mail.tm</a></p>`;
  if(id==='settings')return `<div class="notice">升级只从组件官方 GitHub 发布源下载，并在替换前核对发布摘要中的 SHA-256。Electron、OCR 和界面代码随整个应用安装包升级。</div><div id="versionStatus" class="result">正在读取组件版本…</div><div class="list"><div class="list-item"><span><b>sing-box 网络内核</b><br><small>TUN、路由和代理协议组件</small></span><span><button class="secondary update-check" data-component="singBox">检查</button> <button class="primary update-install" data-component="singBox">升级</button></span></div><div class="list-item"><span><b>yt-dlp 媒体组件</b><br><small>Instagram 公开媒体解析与下载</small></span><span><button class="secondary update-check" data-component="ytDlp">检查</button> <button class="primary update-install" data-component="ytDlp">升级</button></span></div><div class="list-item"><span><b>应用、Electron、OCR 与依赖</b><br><small>为保证版本一致，通过新版安装包整体升级</small></span><button class="secondary" id="openAppReleases">查看项目说明</button></div></div><div id="out"></div>`;
  if(id==='translate')return `<textarea id="translateText" placeholder="输入要翻译的文字"></textarea><div class="form-row"><div class="field"><label>源语言</label><select id="from"><option value="auto">自动检测</option><option value="zh-CN">中文</option><option value="ja">日语</option><option value="en">英语</option></select></div><div class="field"><label>目标语言</label><select id="to"><option value="ja">日语</option><option value="zh-CN">中文</option><option value="en">英语</option></select></div></div><button class="primary" id="goTranslate">在 Google 翻译打开</button>`;
  if(id==='upscale')return imageForm('选择图片后在本机画布中放大，不上传服务器。','upscaleFile')+`<div class="field"><label>倍率</label><select id="scale"><option value="2">2×</option><option value="4">4×</option></select></div><button class="primary" id="doUpscale">放大并预览</button><div id="out"></div>`;
  if(id==='screenshot')return `<div class="notice">截图和 OCR 均在本机处理。OCR 首次使用某种语言时需要下载对应识别数据。</div><div class="actions"><button class="primary" id="takeShot">选择屏幕截图</button></div><div class="field"><label>选择图片提取文字</label><input type="file" id="ocrFile" accept="image/png,image/jpeg,image/webp"></div><div class="form-row"><div class="field"><label>识别语言</label><select id="ocrLanguage"><option value="chi_sim">简体中文</option><option value="jpn">日语</option><option value="eng">英语</option></select></div><div class="field"><label>&nbsp;</label><button class="primary" id="runOcr">开始识别</button></div></div><div id="out"></div>`;
  if(id==='gif')return imageForm('选择 2–30 张图片，按选择顺序生成 GIF。所有帧会统一为第一张图片的尺寸。','gifFiles',true)+`<div class="form-row"><div class="field"><label>每帧时长</label><select id="gifDelay"><option value="200">0.2 秒</option><option value="500" selected>0.5 秒</option><option value="1000">1 秒</option></select></div><div class="field"><label>最大边长</label><select id="gifSize"><option value="480">480 px</option><option value="720" selected>720 px</option><option value="1080">1080 px</option></select></div></div><div class="actions"><button class="primary" id="gifPreview">生成并下载 GIF</button></div><div id="out"></div>`;
  if(id==='ins')return `<div class="notice">仅下载你拥有版权或获授权的公开内容。私密帖子和需要登录的内容不会绕过平台权限。文件保存到系统“下载/Aurora-Toolbox/Instagram”。</div><div class="field"><label>Instagram 帖子或 Reel 链接</label><input id="insUrl" placeholder="https://www.instagram.com/p/..."></div><div class="actions"><button class="secondary" id="checkIns">解析内容</button><button class="primary" id="downloadIns">下载公开媒体</button></div><div id="out"></div>`;
  if(id==='proxy')return `<div class="notice">粘贴节点或扫描二维码后即可测试、保存并连接。内置 sing-box 1.14.0；“TUN 全局模式”会接管游戏、终端和其他程序，启动时仅需确认 Windows 管理员授权。</div><div class="form-row"><div id="proxyStatus" class="result">正在读取系统代理状态…</div><div id="tunStatus" class="result">正在读取 TUN 状态…</div></div><div class="form-row"><div class="field"><label>配置名称</label><input id="proxyName" placeholder="例如：日本节点"></div><div class="field"><label>节点／分享链接</label><input id="proxyText" placeholder="socks5://用户名:密码@主机:端口{日本}proxy"></div></div><div class="field"><label>不使用系统代理的地址（分号分隔）</label><input id="proxyBypass" value="localhost;127.*;10.*;192.168.*;&lt;local&gt;"></div><div class="field"><label>从二维码图片导入</label><input type="file" id="proxyQr" accept="image/*"></div><div class="actions"><button class="secondary" id="scanProxyQr">识别二维码</button><button class="secondary" id="testProxy">测试节点</button><button class="secondary" id="saveProxy">保存配置</button></div><h3>TUN 全局网络（推荐）</h3><div class="actions"><button class="primary" id="startTun">一键全局连接</button><button class="secondary" id="stopTun">断开并恢复网络</button><button class="secondary" id="chooseTunCore">使用其他内核</button></div><h3>Windows 系统代理（兼容模式）</h3><div class="actions"><button class="secondary" id="enableProxy">启用系统代理</button><button class="secondary" id="disableProxy">关闭系统代理</button><button class="secondary" id="proxySettings">系统设置</button></div><h3>已保存配置</h3><div id="proxyProfiles" class="list"></div><div id="out"></div>`;
  if(id==='phrases')return `<div class="field"><input id="phraseSearch" placeholder="搜索日语或中文…"></div><div class="list" id="phraseList">${phraseRows(phrasesBase)}</div>`;
  if(id==='emoji'){const a=['(＾▽＾)','(｡･ω･｡)','(≧▽≦)','(´・ω・`)','(╥﹏╥)','(￣▽￣)','٩(◕‿◕｡)۶','(づ｡◕‿‿◕｡)づ','ʕ•ᴥ•ʔ','(ง •̀_•́)ง'];return `<div class="list">${a.map(x=>`<button class="secondary emoji">${x}</button>`).join('')}</div>`}
  if(simpleInfo[id])return `<div class="list">${simpleInfo[id].map((x,i)=>`<div class="list-item"><span>${x}</span><small>${String(i+1).padStart(2,'0')}</small></div>`).join('')}</div>${id==='cleanup'?'<div class="actions"><button class="primary" id="scanStorage">安全扫描</button><button class="secondary" id="cleanTemp">清理安全临时文件</button><button class="secondary" id="systemSettings">打开存储设置</button></div><div id="out"></div>':id==='hotspot'?'<div class="actions"><button class="primary" id="systemSettings">打开热点设置</button></div>':''}`;
  if(id==='stock')return `<div class="notice">行情来自非官方公开图表端点，可能延迟、中断或存在误差，仅供资料参考，不构成投资建议。正式商业发布应改用 JPX 授权行情。</div><div class="field"><label>日本股票4位证券代码</label><input id="ticker" inputmode="numeric" maxlength="4" placeholder="例如 7203（丰田汽车）"></div><div class="actions"><button class="primary" id="stockCheck">查询近一个月行情</button><button class="secondary stock-example" data-code="7203">7203</button><button class="secondary stock-example" data-code="6758">6758</button><button class="secondary stock-example" data-code="9984">9984</button></div><div id="out"></div>`;
  const links=id==='mail'?[['Gmail','https://mail.google.com/'],['Outlook','https://outlook.live.com/mail/']]:id==='telegram'?[['Telegram Web','https://web.telegram.org/'],['账号与会话管理','https://my.telegram.org/auth']]:[['Telegram','https://web.telegram.org/'],['Gmail','https://mail.google.com/'],['Outlook','https://outlook.live.com/mail/'],['搜狗输入法','https://shurufa.sogou.com/'],['Google 翻译','https://translate.google.com/']];
  return `<div class="notice">登录由官方网站完成，本工具不接触或保存账号密码。</div><div class="list">${links.map(x=>`<button class="list-item link" data-url="${x[1]}"><span>${x[0]}</span><small>打开官方页面 ↗</small></button>`).join('')}</div>`;
}
function generatorForm(label,id,opts,button){return `<div class="field"><label>${label}</label><select id="${id}">${opts}</select></div><button class="primary" id="generate">${button}</button><div id="out"></div>`}
function quantityPicker(){return `<div class="field"><label>生成数量（最低 50 条）</label><input type="hidden" id="amount" value="50"><div class="quantity-picker">${[50,100,200,500].map((n,i)=>`<button type="button" class="quantity-btn ${i?'':'active'}" data-value="${n}">${n}</button>`).join('')}</div></div>`}
function imageForm(note,id,multi=false){return `<div class="notice">${note}</div><div class="field"><input type="file" id="${id}" accept="image/*" ${multi?'multiple':''}></div>`}
function phraseRows(rows){return rows.map((x,i)=>`<div class="list-item"><span><b>${x[0]}</b><br><small>${x[1]}</small></span><button class="secondary copyPhrase" data-text="${x[0]}">复制</button></div>`).join('')}

function bindTool(id){
  document.querySelectorAll('.quantity-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.quantity-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#amount').value=b.dataset.value});
  document.querySelectorAll('.link').forEach(b=>b.onclick=()=>open(b.dataset.url));
  document.querySelectorAll('.emoji').forEach(b=>b.onclick=()=>copy(b.textContent));
  document.querySelectorAll('.copyPhrase').forEach(b=>b.onclick=()=>copy(b.dataset.text));
  if(id==='phone'||id==='address'||id==='enname'||id==='jpname')$('#generate').onclick=()=>generate(id);
  if(id==='counter')$('#text').oninput=e=>{const s=e.target.value, words=(s.trim().match(/[\p{L}\p{N}]+/gu)||[]).length;$('#stats').textContent=`字符 ${s.length} · 不含空格 ${s.replace(/\s/g,'').length} · 单词 ${words} · 行数 ${s? s.split(/\n/).length:0} · 阅读 ${Math.ceil(words/300)} 分钟`};
  if(id==='passwordgen')$('#makePassword').onclick=()=>{const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%&*+-_?',bytes=crypto.getRandomValues(new Uint8Array(Number($('#passLength').value))),v=[...bytes].map(x=>chars[x%chars.length]).join('');$('#out').innerHTML=`<div class="result">${v}</div><button class="secondary" id="copyPassword">复制密码</button>`;$('#copyPassword').onclick=()=>copy(v)};
  if(id==='network')$('#publicIp').onclick=async()=>{try{const r=await fetch('https://api.ipify.org?format=json'),d=await r.json();$('#out').innerHTML=`<div class="result">公网 IP：${d.ip}</div>`}catch{$('#out').innerHTML='<div class="notice">公网查询失败，请检查网络连接。</div>'}};
  if(id==='translate')$('#goTranslate').onclick=()=>open(`https://translate.google.com/?sl=${$('#from').value}&tl=${$('#to').value}&text=${encodeURIComponent($('#translateText').value)}&op=translate`);
  if(id==='phrases')$('#phraseSearch').oninput=e=>{const q=e.target.value;$('#phraseList').innerHTML=phraseRows(phrasesBase.filter(x=>x.join('').includes(q)));bindTool('noop')};
  if(id==='ins'){$('#checkIns').onclick=()=>runInstagram('inspect');$('#downloadIns').onclick=()=>runInstagram('download')}
  if(id==='proxy')bindProxy();
  if(id==='hotspot')$('#systemSettings').onclick=()=>window.toolbox?.setting('hotspot');
  if(id==='cleanup'){$('#systemSettings').onclick=()=>window.toolbox?.setting('storage');$('#scanStorage').onclick=scanStorage;$('#cleanTemp').onclick=cleanSafeTemp}
  if(id==='upscale')$('#doUpscale').onclick=upscale;
  if(id==='gif')$('#gifPreview').onclick=gifPreview;
  if(id==='screenshot'){$('#takeShot').onclick=takeShot;$('#runOcr').onclick=runOcr}
  if(id==='stock'){$('#stockCheck').onclick=loadJapanStock;document.querySelectorAll('.stock-example').forEach(b=>b.onclick=()=>{$('#ticker').value=b.dataset.code;loadJapanStock()})}
  if(id==='notebook')bindNotebook();if(id==='totp')$('#makeTotp').onclick=makeTotp;
  if(id==='tempmail')bindTempMail();
  if(id==='settings')bindSettings();
}
function generate(id){let rows=[];const n=Number($('#amount')?.value||50);if(id==='phone'){const c=countries[$('#country').value];rows=Array.from({length:n},()=>`${c.code} ${digits(c.phone)}`)}if(id==='address'){const c=countries[$('#country').value];rows=Array.from({length:n},()=>`${Math.floor(Math.random()*900)+100} ${rand(c.street)}, ${rand(c.city)}`)}if(id==='enname'){const gender=$('#nameGender').value,region=$('#nameRegion').value,names=gender==='any'?[...englishNames.male,...englishNames.female]:englishNames[gender];rows=Array.from({length:n},()=>`${rand(names)} ${rand(englishLast[region])}`)}if(id==='jpname')rows=Array.from({length:n},()=>{const f=rand(jpFirst),l=rand(jpLast);return `汉字：${l[2]} ${f[2]}\n片假名：${l[1]} ${f[1]}\n罗马字：${f[0]} ${l[0]}\n网名：${f[0].toLowerCase()}_${Math.floor(Math.random()*900+100)}`});$('#out').innerHTML=`<div class="result result-scroll"><b>已生成 ${rows.length} 条</b>\n\n${rows.join('\n\n')}</div><div class="actions"><button class="secondary" id="copyResult">复制全部结果</button></div>`;$('#copyResult').onclick=()=>copy(rows.join('\n'))}
async function upscale(){const f=$('#upscaleFile').files[0];if(!f)return toast('请先选择图片');const img=new Image();img.onload=()=>{const s=Number($('#scale').value),c=document.createElement('canvas');c.width=img.width*s;c.height=img.height*s;c.getContext('2d').drawImage(img,0,0,c.width,c.height);const url=c.toDataURL('image/png');$('#out').innerHTML=`<div class="result">${img.width}×${img.height} → ${c.width}×${c.height}</div><img src="${url}" style="max-width:100%;border-radius:10px;margin-top:12px"><div class="actions"><a class="primary" download="upscaled.png" href="${url}">下载 PNG</a></div>`};img.src=URL.createObjectURL(f)}
async function imageData(file,width,height){const bmp=await createImageBitmap(file),c=document.createElement('canvas');c.width=width;c.height=height;const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,width,height);ctx.drawImage(bmp,0,0,width,height);return [...ctx.getImageData(0,0,width,height).data]}
async function gifPreview(){const fs=[...$('#gifFiles').files];if(fs.length<2)return toast('请至少选择两张图片');if(fs.length>30)return toast('一次最多选择 30 张');const btn=$('#gifPreview');btn.disabled=true;btn.textContent='正在编码…';try{const first=await createImageBitmap(fs[0]),max=Number($('#gifSize').value),ratio=Math.min(1,max/Math.max(first.width,first.height)),width=Math.max(1,Math.round(first.width*ratio)),height=Math.max(1,Math.round(first.height*ratio)),frames=[];for(let i=0;i<fs.length;i++){btn.textContent=`处理第 ${i+1}/${fs.length} 帧…`;frames.push({data:await imageData(fs[i],width,height)})}const base64=await window.toolbox.makeGif({frames,width,height,delay:Number($('#gifDelay').value)}),url=`data:image/gif;base64,${base64}`;$('#out').innerHTML=`<div class="result">生成成功 · ${width}×${height} · ${fs.length} 帧</div><img src="${url}" style="max-width:100%;border-radius:10px;margin-top:12px"><div class="actions"><a class="primary" download="animation.gif" href="${url}">下载 GIF</a></div>`}catch(e){$('#out').innerHTML=`<div class="notice">GIF 生成失败：${e.message||'请确认已安装依赖并使用 Electron 模式'}</div>`}finally{btn.disabled=false;btn.textContent='生成并下载 GIF'}}
async function takeShot(){try{const rows=await window.toolbox.screens();$('#out').innerHTML=rows.slice(0,6).map((x,i)=>`<div style="margin:12px 0"><b>${x.name}</b><img src="${x.dataURL}" style="width:100%;margin-top:8px;border-radius:9px"><div class="actions"><a class="secondary" href="${x.dataURL}" download="screenshot-${i+1}.png">下载截图</a></div></div>`).join('')}catch{$('#out').innerHTML='<div class="notice">截图需要使用 Electron 桌面模式启动。</div>'}}
async function runOcr(){const f=$('#ocrFile').files[0];if(!f)return toast('请先选择图片');const btn=$('#runOcr');btn.disabled=true;btn.textContent='识别中…';try{const base64=await fileBase64(f),r=await window.toolbox.ocr({base64,language:$('#ocrLanguage').value});$('#out').innerHTML=`<div class="result">识别可信度：${Math.round(r.confidence||0)}%\n\n${escapeHtml(r.text||'未识别到文字')}</div><button class="secondary" id="copyOcr">复制文字</button>`;$('#copyOcr').onclick=()=>copy(r.text)}catch(e){$('#out').innerHTML=`<div class="notice">OCR 失败：${e.message||'请检查网络或依赖'}</div>`}finally{btn.disabled=false;btn.textContent='开始识别'}}
function fileBase64(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file)})}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function stockChart(points){if(points.length<2)return '';const w=700,h=210,p=16,vals=points.map(x=>x.close),min=Math.min(...vals),max=Math.max(...vals),span=max-min||1,path=points.map((x,i)=>`${i?'L':'M'} ${(p+i*(w-p*2)/(points.length-1)).toFixed(1)} ${(h-p-(x.close-min)*(h-p*2)/span).toFixed(1)}`).join(' '),up=vals.at(-1)>=vals[0];return `<svg viewBox="0 0 ${w} ${h}" style="width:100%;margin-top:14px;background:#07131f;border-radius:10px"><path d="${path}" fill="none" stroke="${up?'#4ce4d0':'#ff7187'}" stroke-width="3"/><text x="16" y="25" fill="#8296aa" font-size="12">¥${max.toFixed(2)}</text><text x="16" y="195" fill="#8296aa" font-size="12">¥${min.toFixed(2)}</text></svg>`}
async function loadJapanStock(){const code=$('#ticker').value.trim(),btn=$('#stockCheck');if(!/^\d{4}$/.test(code))return toast('请输入4位证券代码');btn.disabled=true;btn.textContent='查询中…';try{const r=await window.toolbox.japanStock({code}),change=r.change??0,positive=change>=0,time=r.marketTime?new Date(r.marketTime*1000).toLocaleString('zh-CN',{timeZone:'Asia/Tokyo'}):'未知';$('#out').innerHTML=`<div class="result"><b>${escapeHtml(r.symbol)} · ${escapeHtml(r.exchange)}</b>\n最新参考价：¥${Number(r.price).toFixed(2)}\n涨跌：<span style="color:${positive?'var(--cyan)':'var(--red)'}">${positive?'+':''}${change.toFixed(2)} (${positive?'+':''}${(r.changePercent??0).toFixed(2)}%)</span>\n市场时间：${time}\n币种：${escapeHtml(r.currency)}\n数据源：${escapeHtml(r.source)}</div>${stockChart(r.points)}<div class="result">研究清单\n1. 阅读最新决算短信与有价证券报告书\n2. 对比营收、营业利润、现金流与 ROE\n3. 检查估值、负债、股息和汇率敏感度\n4. 通过 TDnet 核对公司最新披露</div>`}catch(e){$('#out').innerHTML=`<div class="notice">查询失败：${escapeHtml(e.message)}</div>`}finally{btn.disabled=false;btn.textContent='查询近一个月行情'}}
async function runInstagram(action){const url=$('#insUrl').value.trim(),btn=$(action==='inspect'?'#checkIns':'#downloadIns');if(!/^https:\/\/(www\.)?instagram\.com\/(p|reel|reels|tv)\//i.test(url))return toast('请输入有效的 Instagram 链接');btn.disabled=true;btn.textContent=action==='inspect'?'解析中…':'下载中…';try{const r=await window.toolbox.instagram({action,url});$('#out').innerHTML=action==='inspect'?`<div class="result">标题：${escapeHtml(r.title)}\n发布者：${escapeHtml(r.uploader||'未知')}\n媒体数量：${r.count}\n类型：${escapeHtml(r.type)}</div>`:`<div class="result">下载完成\n目录：${escapeHtml(r.destination)}\n${r.files.map(x=>escapeHtml(x)).join('\n')}</div>`}catch(e){$('#out').innerHTML=`<div class="notice">${action==='inspect'?'解析':'下载'}失败：${escapeHtml(e.message||'公开内容可能需要登录')}</div>`}finally{btn.disabled=false;btn.textContent=action==='inspect'?'解析内容':'下载公开媒体'}}
let tempMailSession=null;
function bindTempMail(){
  $('#mailTmLink').onclick=e=>{e.preventDefault();open('https://mail.tm/')};
  $('#createTempMail').onclick=async()=>{const btn=$('#createTempMail');btn.disabled=true;btn.textContent='创建中…';try{tempMailSession=await window.toolbox.tempMail({action:'create'});$('#tempIdentity').textContent=tempMailSession.address;$('#copyTempMail').disabled=false;$('#refreshTempMail').disabled=false;$('#out').innerHTML='<div class="result">邮箱已创建，正在等待邮件…</div>';toast('临时邮箱创建成功')}catch(e){$('#out').innerHTML=`<div class="notice">创建失败：${escapeHtml(e.message||'网络不可用')}</div>`}finally{btn.disabled=false;btn.textContent='创建新邮箱'}};
  $('#copyTempMail').onclick=()=>tempMailSession&&copy(tempMailSession.address);
  $('#refreshTempMail').onclick=refreshTempMail;
}
async function refreshTempMail(){if(!tempMailSession)return;const btn=$('#refreshTempMail');btn.disabled=true;btn.textContent='刷新中…';try{const rows=await window.toolbox.tempMail({action:'messages',token:tempMailSession.token});$('#out').innerHTML=rows.length?`<div class="list">${rows.map(m=>`<button class="list-item temp-message" data-id="${m.id}"><span><b>${escapeHtml(m.subject)}</b><br><small>${escapeHtml(m.from)} · ${new Date(m.createdAt).toLocaleString()}</small><br><small>${escapeHtml(m.intro)}</small></span><small>查看 →</small></button>`).join('')}</div>`:'<div class="result">暂时没有新邮件。可稍后点击刷新。</div>';document.querySelectorAll('.temp-message').forEach(b=>b.onclick=()=>readTempMessage(b.dataset.id))}catch(e){$('#out').innerHTML=`<div class="notice">刷新失败：${escapeHtml(e.message)}</div>`}finally{btn.disabled=false;btn.textContent='刷新收件箱'}}
async function readTempMessage(id){try{const m=await window.toolbox.tempMail({action:'message',token:tempMailSession.token,id});$('#out').innerHTML=`<button class="secondary" id="backInbox">← 返回收件箱</button><div class="result"><b>${escapeHtml(m.subject)}</b>\n来自：${escapeHtml(m.from)}\n时间：${new Date(m.createdAt).toLocaleString()}\n\n${escapeHtml(m.text||'邮件没有纯文本内容')}</div>`;$('#backInbox').onclick=refreshTempMail}catch(e){toast(`读取失败：${e.message}`)}}
function bindSettings(){const status=$('#versionStatus');status.insertAdjacentHTML('afterend','<h3>应用一键升级</h3><div class="actions"><button class="secondary" id="checkAppUpdate">检查应用更新</button><button class="primary" id="installAppUpdate">一键升级并重启</button></div><div id="appUpdateStatus"></div><h3>桌面与外观</h3><div class="actions"><button class="secondary" id="toggleTheme">切换深色／浅色</button><button class="secondary" id="toggleStartup">读取开机启动状态</button><button class="secondary" id="openLogs">打开日志目录</button></div><h3>组件升级</h3>');document.querySelectorAll('.update-check').forEach(b=>b.onclick=()=>checkComponent(b.dataset.component,b));document.querySelectorAll('.update-install').forEach(b=>b.onclick=()=>installComponent(b.dataset.component,b));$('#openAppReleases').onclick=()=>{$('#out').innerHTML='<div class="result">应用主体通过 GitHub Releases 整体升级。安装版自动运行静默更新；便携版自动替换当前程序并重启。用户数据和已升级组件保留在本机用户目录。</div>'};$('#checkAppUpdate').onclick=checkAppUpdate;$('#installAppUpdate').onclick=installAppUpdate;$('#toggleTheme').onclick=toggleTheme;$('#toggleStartup').onclick=toggleStartup;$('#openLogs').onclick=()=>window.toolbox.desktopSettings({action:'openLogs'});refreshVersions();refreshDesktopSettings()}
let latestAppUpdate=null;
async function checkAppUpdate(){const btn=$('#checkAppUpdate');btn.disabled=true;btn.textContent='检查中…';try{latestAppUpdate=await window.toolbox.appUpdate({action:'check'});$('#appUpdateStatus').innerHTML=`<div class="result">当前版本：${escapeHtml(latestAppUpdate.current)}\n最新版本：${escapeHtml(latestAppUpdate.latest)}\n状态：${latestAppUpdate.available?'发现新版本':'已经是最新版'}\n发布时间：${new Date(latestAppUpdate.publishedAt).toLocaleString()}\n文件：${escapeHtml(latestAppUpdate.asset)}\n大小：${humanBytes(latestAppUpdate.size)}\n来源：GitHub · ${escapeHtml(latestAppUpdate.repository)}</div>`}catch(e){$('#appUpdateStatus').innerHTML=`<div class="notice">检查失败：${escapeHtml(e.message)}</div>`}finally{btn.disabled=false;btn.textContent='检查应用更新'}}
async function installAppUpdate(){if(!latestAppUpdate){await checkAppUpdate();if(!latestAppUpdate)return}if(!latestAppUpdate.available&&!confirm('当前已经是最新版，仍要重新下载并安装吗？'))return;if(!confirm(`即将下载 ${latestAppUpdate.latest}，校验后自动退出、升级并重启。是否继续？`))return;const btn=$('#installAppUpdate');btn.disabled=true;btn.textContent='下载与校验中…';try{const r=await window.toolbox.appUpdate({action:'download'});$('#appUpdateStatus').innerHTML=`<div class="result">下载完成并通过校验\n版本：${escapeHtml(r.version)}\nSHA-256：${escapeHtml(r.digest)}\n正在退出并完成替换…</div>`;await window.toolbox.applyAppUpdate(r)}catch(e){$('#appUpdateStatus').innerHTML=`<div class="notice">升级失败：${escapeHtml(e.message)}</div>`;btn.disabled=false;btn.textContent='一键升级并重启'}}
function toggleTheme(){const light=document.body.classList.toggle('light');localStorage.setItem('theme',light?'light':'dark');toast(light?'已切换浅色主题':'已切换深色主题')}
async function refreshDesktopSettings(){try{const r=await window.toolbox.desktopSettings({action:'status'}),b=$('#toggleStartup');b.dataset.enabled=String(r.launchAtLogin);b.textContent=r.launchAtLogin?'关闭开机启动':'开启开机启动'}catch{}}
async function toggleStartup(){const b=$('#toggleStartup'),enabled=b.dataset.enabled!=='true';try{await window.toolbox.desktopSettings({action:'launchAtLogin',enabled});refreshDesktopSettings();toast(enabled?'已开启开机启动':'已关闭开机启动')}catch(e){toast(`设置失败：${e.message}`)}}
async function refreshVersions(){try{const r=await window.toolbox.updates({action:'status'});$('#versionStatus').innerHTML=`应用：${escapeHtml(r.app)}\nElectron：${escapeHtml(r.electron)}\nNode.js：${escapeHtml(r.node)}\nsing-box：${escapeHtml(r.singBox)}\nyt-dlp：${escapeHtml(r.ytDlp)}\n\n组件升级目录：${escapeHtml(r.locations.tools)}`}catch(e){$('#versionStatus').textContent=`读取失败：${e.message}`}}
async function checkComponent(component,btn){btn.disabled=true;btn.textContent='检查中…';try{const r=await window.toolbox.updates({action:'check',component});$('#out').innerHTML=`<div class="result">${component==='singBox'?'sing-box':'yt-dlp'} 最新版本：${escapeHtml(r.latest)}\n发布时间：${new Date(r.publishedAt).toLocaleString()}\n文件：${escapeHtml(r.asset)}\n大小：${humanBytes(r.size)}\n校验：${escapeHtml(r.digest||'发布方未提供')}</div>`}catch(e){$('#out').innerHTML=`<div class="notice">检查失败：${escapeHtml(e.message)}</div>`}finally{btn.disabled=false;btn.textContent='检查'}}
async function installComponent(component,btn){if(!confirm(`将从官方发布源下载并升级 ${component==='singBox'?'sing-box':'yt-dlp'}。校验失败时不会安装，是否继续？`))return;btn.disabled=true;btn.textContent='升级中…';try{const r=await window.toolbox.updates({action:'install',component});$('#out').innerHTML=`<div class="result">升级成功\n版本：${escapeHtml(r.version)}\nSHA-256：${escapeHtml(r.digest)}\n位置：${escapeHtml(r.location)}</div>`;refreshVersions()}catch(e){$('#out').innerHTML=`<div class="notice">升级失败：${escapeHtml(e.message)}</div>`}finally{btn.disabled=false;btn.textContent='升级'}}
async function scanProxyQr(){const f=$('#proxyQr').files[0];if(!f)return toast('请先选择二维码图片');if(!('BarcodeDetector'in window)){return $('#out').innerHTML='<div class="notice">当前系统不支持原生二维码识别。可直接粘贴节点文本。</div>'}try{const bitmap=await createImageBitmap(f),detector=new BarcodeDetector({formats:['qr_code']}),codes=await detector.detect(bitmap);if(!codes.length)throw Error();$('#proxyText').value=codes[0].rawValue;$('#out').innerHTML='<div class="result">二维码识别成功，请检查节点内容后保存。</div>'}catch{$('#out').innerHTML='<div class="notice">没有识别到二维码，请换一张清晰图片。</div>'}}
function proxyProfiles(){try{return JSON.parse(localStorage.getItem('proxy-profiles'))||[]}catch{return[]}}
function normalizedProxy(v){return String(v).trim().replace(/\{[^}]*\}proxy\s*$/i,'').replace(/@\[(\d{1,3}(?:\.\d{1,3}){3})\](?=:)/,'@$1')}
function validProxyUrl(v){try{const u=new URL(normalizedProxy(v));return ['http:','https:','socks5:'].includes(u.protocol)&&u.hostname&&u.port}catch{return false}}
function maskedProxy(v){try{const u=new URL(normalizedProxy(v));if(u.username||u.password){u.username='***';u.password='***'}return u.toString()}catch{return '无效节点'}}
function bindProxy(){
  const legacy=localStorage.getItem('proxy-config');if(legacy)$('#proxyText').value=legacy;
  $('#proxySettings').onclick=()=>window.toolbox?.setting('proxy');$('#scanProxyQr').onclick=scanProxyQr;$('#enableProxy').onclick=enableSystemProxy;$('#disableProxy').onclick=disableSystemProxy;$('#testProxy').onclick=testSystemProxy;$('#saveProxy').onclick=saveProxyProfile;$('#chooseTunCore').onclick=chooseTunCore;$('#startTun').onclick=startTun;$('#stopTun').onclick=stopTun;
  renderProxyProfiles();refreshProxyStatus();refreshTunStatus();
}
async function refreshProxyStatus(){try{const r=await window.toolbox.proxy({action:'status'});$('#proxyStatus').innerHTML=r.enabled?`<b style="color:var(--cyan)">● 已启用</b>　${escapeHtml(r.server||'未知服务器')}<br><small>绕过：${escapeHtml(r.bypass||'无')}</small>`:'<b style="color:var(--muted)">○ 已关闭</b>　当前使用直接连接'}catch{$('#proxyStatus').textContent='无法读取系统代理状态'} }
function saveProxyProfile(){const name=$('#proxyName').value.trim()||`代理 ${proxyProfiles().length+1}`,url=$('#proxyText').value.trim(),bypass=$('#proxyBypass').value.trim();if(!validProxyUrl(url))return $('#out').innerHTML='<div class="notice">请输入带端口且不含账号密码的 HTTP、HTTPS 或 SOCKS5 地址。</div>';const rows=proxyProfiles(),existing=rows.findIndex(x=>x.name===name);const item={id:existing>=0?rows[existing].id:String(Date.now()),name,url,bypass};if(existing>=0)rows[existing]=item;else rows.push(item);localStorage.setItem('proxy-profiles',JSON.stringify(rows.slice(-30)));localStorage.setItem('proxy-config',url);renderProxyProfiles();toast('代理配置已保存')}
function renderProxyProfiles(){const box=$('#proxyProfiles');if(!box)return;const rows=proxyProfiles();box.innerHTML=rows.length?rows.map(x=>`<div class="list-item"><span><b>${escapeHtml(x.name)}</b><br><small>${escapeHtml(maskedProxy(x.url))}</small></span><span><button class="secondary proxy-use" data-id="${x.id}">载入</button> <button class="secondary proxy-delete" data-id="${x.id}">删除</button></span></div>`).join(''):'<div class="result">暂无保存的配置</div>';document.querySelectorAll('.proxy-use').forEach(b=>b.onclick=()=>{const x=proxyProfiles().find(p=>p.id===b.dataset.id);if(x){$('#proxyName').value=x.name;$('#proxyText').value=x.url;$('#proxyBypass').value=x.bypass||'<local>';toast('配置已载入')}});document.querySelectorAll('.proxy-delete').forEach(b=>b.onclick=()=>{const rows=proxyProfiles().filter(p=>p.id!==b.dataset.id);localStorage.setItem('proxy-profiles',JSON.stringify(rows));renderProxyProfiles()})}
async function testSystemProxy(){const url=$('#proxyText').value.trim(),btn=$('#testProxy');if(!validProxyUrl(url))return toast('节点格式无效');btn.disabled=true;btn.textContent='测试中…';try{const r=await window.toolbox.proxy({action:'test',url});$('#out').innerHTML=`<div class="result"><b style="color:var(--cyan)">节点可连接</b>\nTCP 延迟：${r.latency} ms\n\n提示：端口可连接不代表代理协议或账号一定有效。</div>`}catch(e){$('#out').innerHTML=`<div class="notice">测试失败：${escapeHtml(e.message)}</div>`}finally{btn.disabled=false;btn.textContent='测试节点'}}
async function enableSystemProxy(){const url=$('#proxyText').value.trim(),bypass=$('#proxyBypass').value.trim();if(!validProxyUrl(url))return toast('节点格式无效');if(!confirm(`即将把 Windows 系统代理切换为：\n${url}\n\n如果节点不可用可能导致网络中断，是否继续？`))return;try{const r=await window.toolbox.proxy({action:'enable',url,bypass});localStorage.setItem('proxy-config',url);$('#out').innerHTML=`<div class="result">系统代理已启用\n服务器：${escapeHtml(r.server)}\n协议：${escapeHtml(r.protocol)}\n绕过：${escapeHtml(r.bypass)}\n\n网络异常时请点击“关闭”。</div>`;refreshProxyStatus()}catch(e){$('#out').innerHTML=`<div class="notice">启用失败：${escapeHtml(e.message)}</div>`}}
async function disableSystemProxy(){if(!confirm('确认关闭 Windows 系统代理？'))return;try{await window.toolbox.proxy({action:'disable'});$('#out').innerHTML='<div class="result">系统代理已关闭，已恢复直接连接。</div>';refreshProxyStatus()}catch(e){$('#out').innerHTML=`<div class="notice">关闭失败：${escapeHtml(e.message)}</div>`}}
async function refreshTunStatus(){try{const r=await window.toolbox.tun({action:'status'});$('#tunStatus').innerHTML=r.running?`<b style="color:var(--cyan)">● TUN 全局运行中</b><br><small>进程 ${r.pid} · ${r.bundled?'内置内核':'自定义内核'}</small>`:`<b style="color:var(--muted)">○ TUN 未运行</b><br><small>${r.core?(r.bundled?'内置内核已就绪':'自定义内核已就绪'):'内核缺失'}</small>`}catch{$('#tunStatus').textContent='无法读取 TUN 状态'}}
async function chooseTunCore(){try{const r=await window.toolbox.chooseTunCore();if(r){$('#out').innerHTML=`<div class="result">内核验证成功\n${escapeHtml(r.version)}\n${escapeHtml(r.core)}</div>`;refreshTunStatus()}}catch(e){$('#out').innerHTML=`<div class="notice">内核验证失败：${escapeHtml(e.message)}</div>`}}
async function startTun(){const url=$('#proxyText').value.trim();if(!validProxyUrl(url))return toast('请先填写有效的上游节点');if(!confirm(`即将创建 TUN 虚拟网卡并接管全部网络流量。\n上游：${maskedProxy(url)}\n局域网地址保持直连。\n\nWindows 将请求管理员权限，是否继续？`))return;const btn=$('#startTun');btn.disabled=true;btn.textContent='启动中…';try{const r=await window.toolbox.tun({action:'start',url});$('#out').innerHTML=`<div class="result">TUN 全局网络已启动\n进程：${r.pid}\n\n如出现网络异常，请立即点击“停止全局 TUN”。</div>`;refreshTunStatus()}catch(e){$('#out').innerHTML=`<div class="notice">TUN 启动失败：${escapeHtml(e.message)}</div>`}finally{btn.disabled=false;btn.textContent='启动全局 TUN'}}
async function stopTun(){if(!confirm('停止 TUN 并恢复原网络路由？'))return;try{await window.toolbox.tun({action:'stop'});$('#out').innerHTML='<div class="result">TUN 已停止，系统路由将恢复。</div>';refreshTunStatus()}catch(e){$('#out').innerHTML=`<div class="notice">停止失败：${escapeHtml(e.message)}</div>`}}
const humanBytes=n=>n==null?'未知':n>1073741824?`${(n/1073741824).toFixed(2)} GB`:n>1048576?`${(n/1048576).toFixed(1)} MB`:`${Math.round(n/1024)} KB`;
async function scanStorage(){const btn=$('#scanStorage');btn.disabled=true;btn.textContent='扫描中…';try{const d=await window.toolbox.storage();$('#out').innerHTML=`<div class="result">${d.drive} 盘容量：${humanBytes(d.disk?.total)}\n可用空间：${humanBytes(d.disk?.free)}\n\n${d.areas.map(a=>`${a.name}\n${a.dir}\n${a.files} 个文件 · ${humanBytes(a.bytes)}${a.capped?' · 已达到扫描上限':''}`).join('\n\n')}\n\n本次仅扫描，没有删除任何文件。</div>`}catch{$('#out').innerHTML='<div class="notice">扫描失败，请使用 Electron 桌面模式运行。</div>'}finally{btn.disabled=false;btn.textContent='重新扫描'}}
async function cleanSafeTemp(){if(!confirm('只会删除用户临时目录和 Windows Temp 中超过 24 小时、当前未被占用的文件。\n\n删除后通常无法恢复，是否继续？'))return;const btn=$('#cleanTemp');btn.disabled=true;btn.textContent='清理中…';try{const r=await window.toolbox.cleanTemp();$('#out').innerHTML=`<div class="result">安全清理完成\n删除文件：${r.removed} 个\n释放空间：${humanBytes(r.freed)}\n跳过文件：${r.skipped} 个\n策略：${r.policy}</div>`}catch(e){$('#out').innerHTML=`<div class="notice">清理失败：${escapeHtml(e.message||'权限不足')}</div>`}finally{btn.disabled=false;btn.textContent='再次清理'}}
async function derive(password,salt){const base=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:120000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
const b64=a=>btoa(String.fromCharCode(...new Uint8Array(a))), unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
function bindNotebook(){$('#saveNote').onclick=async()=>{if(!$('#password').value)return toast('请输入密码');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await derive($('#password').value,salt),data=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode($('#note').value));localStorage.setItem('secure-note',JSON.stringify({salt:b64(salt),iv:b64(iv),data:b64(data)}));toast('已加密保存')};$('#loadNote').onclick=async()=>{try{const x=JSON.parse(localStorage.getItem('secure-note')),key=await derive($('#password').value,unb64(x.salt)),data=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(x.iv)},key,unb64(x.data));$('#note').value=new TextDecoder().decode(data);toast('解锁成功')}catch{toast('密码错误或没有已保存内容')}};$('#clearNote').onclick=()=>{$('#note').value=''}}
function base32(s){const A='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits='';for(const c of s.toUpperCase().replace(/=|\s/g,'')){const i=A.indexOf(c);if(i<0)throw Error();bits+=i.toString(2).padStart(5,'0')}const out=[];for(let i=0;i+8<=bits.length;i+=8)out.push(parseInt(bits.slice(i,i+8),2));return new Uint8Array(out)}
async function makeTotp(){try{const key=await crypto.subtle.importKey('raw',base32($('#secret').value),{name:'HMAC',hash:'SHA-1'},false,['sign']),counter=Math.floor(Date.now()/30000),buf=new ArrayBuffer(8),v=new DataView(buf);v.setUint32(4,counter);const h=new Uint8Array(await crypto.subtle.sign('HMAC',key,buf)),o=h[19]&15,num=(((h[o]&127)<<24)|(h[o+1]<<16)|(h[o+2]<<8)|h[o+3])%1000000;$('#out').innerHTML=`<div class="result" style="font-size:34px;text-align:center;letter-spacing:8px">${String(num).padStart(6,'0')}</div>`}catch{$('#out').innerHTML='<div class="notice">Base32 密钥格式无效。</div>'}}
